name: Serenity Screenplay Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Gradle
        run: ./gradlew clean test

      - name: Copy test report to artifacts
        run: cp -r build/reports/tests/test ${{ github.workspace }}/test-report

      - name: Archive Rest Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: GradleReports/emailable-report.html