name: Serenity Screenplay Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew test

      - name: Copy test report to artifacts
        run: cp -r build/reports/tests/test ${{ github.workspace }}/test-report

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ${{ github.workspace }}/test-report
